/*
 * Successor Console — knowledge pack assembly. Pure: turns derivation
 * results into a file plan ({name, kind, doc|text|json}); the task pane
 * renders docx models with Docx.buildDocx + JSZip and uploads via Graph.
 *
 * Format rules (from RESEARCH.md): .docx only — .md is not usable agent
 * knowledge; every file stays small (unlicensed tenants skip SharePoint
 * files over 7 MB); one topic per file, concise, verbatim + source links.
 */
/* global module */
(function (root) {
  "use strict";

  function fmtDate(iso) { return String(iso || "").slice(0, 10); }

  function safeName(s, max) {
    return String(s || "untitled").replace(/[^A-Za-z0-9 _-]+/g, " ")
      .replace(/\s+/g, " ").trim().slice(0, max || 60).trim() || "untitled";
  }

  function excerpt(text, max) {
    var t = String(text || "").trim();
    return t.length > (max || 1500) ? t.slice(0, max || 1500) + " […]" : t;
  }

  function manifestDoc(ctx) {
    return {
      title: "Knowledge Pack — " + ctx.ownerName,
      blocks: [
        { type: "kv", key: "Source mailbox", value: ctx.ownerAddress },
        { type: "kv", key: "Date range scanned", value: ctx.rangeLabel },
        { type: "kv", key: "Generated on", value: ctx.generatedOn },
        { type: "kv", key: "Generated by", value: "Successor Console (PurposeBuilt Systems) — deterministic extraction, no AI" },
        { type: "kv", key: "Contents", value: ctx.contentsLabel },
        { type: "h1", text: "Provenance statement" },
        { type: "p", text: "Every excerpt in this pack is a verbatim copy of correspondence from the source mailbox, accompanied by a link to the source email. Nothing in this pack was summarized, paraphrased, or generated. Any AI agent configured over this pack reads it at question time and must cite the source links; it never modifies the record." },
        { type: "h1", text: "Review sign-off" },
        { type: "p", text: "Before this pack is used as agent knowledge or shared, a human reviewer should read each file and delete anything that should not become institutional knowledge (personnel matters, confidential communications, drafts)." },
        { type: "p", text: "Reviewed by: _________________________    Date: _____________" },
        { type: "p", text: "Notes / files removed during review: " },
      ],
    };
  }

  function peopleDoc(ctx) {
    var blocks = [
      { type: "p", text: "The people " + ctx.ownerName + " actually corresponded with, most active first. Counts cover the scanned range (" + ctx.rangeLabel + ")." },
    ];
    (ctx.correspondents || []).slice(0, 50).forEach(function (p) {
      blocks.push({ type: "h2", text: p.name + " — " + p.email });
      blocks.push({
        type: "p",
        text: p.total + " emails (" + p.sentTo + " sent to them, " + p.receivedFrom +
          " received), " + fmtDate(p.first) + " to " + fmtDate(p.last) + ".",
      });
    });
    return { title: "People — who " + ctx.ownerName + " worked with", blocks: blocks };
  }

  function openItemsDoc(ctx) {
    var blocks = [
      { type: "p", text: "Conversations that were still open at the end of the scanned range — the live handoff list." },
      { type: "h1", text: "They never answered " + ctx.ownerName + " (" + (ctx.openWaiting || []).length + ")" },
    ];
    (ctx.openWaiting || []).forEach(function (it) {
      blocks.push({ type: "h2", text: it.subject });
      blocks.push({ type: "p", text: "Asked " + fmtDate(it.date) + " to " + it.who + ": " + excerpt(it.text, 300) });
      if (it.webLink) { blocks.push({ type: "link", text: "Open the source email", url: it.webLink }); }
    });
    blocks.push({ type: "h1", text: "Waiting on an answer from the mailbox (" + (ctx.openOwed || []).length + ")" });
    (ctx.openOwed || []).forEach(function (it) {
      blocks.push({ type: "h2", text: it.subject });
      blocks.push({ type: "p", text: "Asked by " + it.who + " on " + fmtDate(it.date) + ": " + excerpt(it.text, 300) });
      if (it.webLink) { blocks.push({ type: "link", text: "Open the source email", url: it.webLink }); }
    });
    return { title: "Open items at departure", blocks: blocks };
  }

  function projectsDoc(ctx) {
    var blocks = [
      { type: "p", text: "Recurring topics in the mailbox, busiest first. Use these as the map of what " + ctx.ownerName + " actually worked on." },
    ];
    (ctx.topics || []).slice(0, 60).forEach(function (t) {
      blocks.push({ type: "h2", text: t.label });
      blocks.push({
        type: "p",
        text: t.count + " emails across " + t.conversations + " conversations, " +
          fmtDate(t.first) + " to " + fmtDate(t.last) + ".",
      });
    });
    return { title: "Topics and projects", blocks: blocks };
  }

  function attachmentsDoc(ctx) {
    var blocks = [
      { type: "p", text: "Files that arrived by email, newest first (metadata only — the files themselves remain on the emails). Use the links to open the carrying email." },
    ];
    (ctx.attachments || []).slice(0, 200).forEach(function (a) {
      blocks.push({ type: "h2", text: a.name });
      blocks.push({
        type: "p",
        text: (a.size ? Math.round(a.size / 1024) + " KB, " : "") +
          fmtDate(a.date) + ", from " + a.from + " — “" + a.subject + "”",
      });
      if (a.webLink) { blocks.push({ type: "link", text: "Open the carrying email", url: a.webLink }); }
    });
    return { title: "Attachment index", blocks: blocks };
  }

  function precedentTopicDoc(ctx, topicKey, pairs) {
    var label = pairs[0].subject;
    var blocks = [
      { type: "p", text: "Real questions and " + ctx.ownerName + "'s real answers on this topic — verbatim, with source links. These are the citable precedents." },
    ];
    pairs.forEach(function (p) {
      blocks.push({ type: "h2", text: fmtDate(p.question.date) + " — asked by " + p.question.from });
      blocks.push({ type: "quote", text: "Q: " + excerpt(p.question.text, 700) });
      if (p.question.webLink) { blocks.push({ type: "link", text: "Source: the question email", url: p.question.webLink }); }
      blocks.push({ type: "p", text: "A (" + fmtDate(p.answer.date) + "): " + excerpt(p.answer.bodyText || p.answer.text, 1800) });
      if (p.answer.webLink) { blocks.push({ type: "link", text: "Source: " + ctx.ownerName + "'s answer", url: p.answer.webLink }); }
    });
    return { title: "Precedents — " + label, blocks: blocks };
  }

  function interviewDoc(ctx) {
    var blocks = [
      { type: "p", text: "Deterministic gap analysis found topics with real traffic but little written knowledge. Ask " + ctx.ownerName + " these questions BEFORE they leave; type or paste the answers under each question, save this file back into the pack, and the answers become first-class knowledge." },
    ];
    (ctx.gaps || []).forEach(function (g, i) {
      blocks.push({ type: "h2", text: (i + 1) + ". " + g.topic + (g.kind === "tacit" ? " (phone-call tell)" : " (thin written record)") });
      blocks.push({ type: "p", text: g.prompt });
      blocks.push({ type: "p", text: "Answer: " });
      blocks.push({ type: "p", text: " " });
    });
    if (!(ctx.gaps || []).length) {
      blocks.push({ type: "p", text: "No significant gaps detected — the written record covers the busy topics." });
    }
    return { title: "Exit interview — " + ctx.ownerName, blocks: blocks };
  }

  function readmeText(ctx) {
    return [
      "KNOWLEDGE PACK — " + ctx.ownerName,
      "Generated " + ctx.generatedOn + " from " + ctx.ownerAddress + " (" + ctx.rangeLabel + ")",
      "",
      "STEP 1 — REVIEW (required before any agent is created)",
      "  Read each .docx and delete anything that should not become institutional",
      "  knowledge. Sign the review line in manifest.docx.",
      "",
      "STEP 2 — CREATE THE AGENT (30 seconds, SharePoint)",
      "  Put this folder in a SharePoint document library (if it isn't already).",
      "  Select the folder -> 'Create an agent'. Done: the agent answers only from",
      "  these files and respects the folder's permissions.",
      "  Preflights: your org needs Microsoft 365 Copilot (any one license) or",
      "  pay-as-you-go agent billing; 'Restricted SharePoint Search' must be OFF;",
      "  newly uploaded files take a few minutes to index.",
      "  A ready-made agent file ('Ask the Archive.agent') may be in this folder —",
      "  it is best-effort (the format is community-documented); if it doesn't",
      "  open, use the manual step above, it is the supported path.",
      "",
      "STEP 3 — ACCESS = THE FOLDER'S PERMISSIONS",
      "  Whoever can read this folder can get answers from the agent. Lock the",
      "  folder to the successor(s) before creating the agent.",
      "",
      "AGENT GROUND RULES (already in the .agent file; repeat them if you create",
      "the agent manually): answer only from these files; always cite the source",
      "email link; say 'not in the archive' otherwise; never speak as " + ctx.ownerName + ".",
      "",
      "See REVIEW-PROMPTS.txt for optional Copilot prompts that help with review.",
      "Generated by Successor Console (PurposeBuilt Systems). Deterministic",
      "extraction - no AI wrote any of this content.",
    ].join("\r\n");
  }

  function reviewPromptsText(ctx) {
    return [
      "OPTIONAL COPILOT PROMPTS FOR THE REVIEW PASS",
      "Paste these into your own Microsoft 365 Copilot while reviewing the pack.",
      "They help ORGANIZE the review - the pack's content stays verbatim; apply",
      "any suggestion yourself, by hand, during review.",
      "",
      "1. \"Read the files in this folder and list any content that looks like",
      "   personnel matters, medical information, legal advice, or confidential",
      "   negotiations that a records reviewer should consider removing.\"",
      "",
      "2. \"Read the Precedents files and propose better topic groupings or",
      "   titles where the current grouping seems off.\"",
      "",
      "3. \"Read 'Exit interview - " + ctx.ownerName + ".docx' and suggest any obvious",
      "   follow-up questions a successor would still need answered.\"",
      "",
      "4. \"List the five topics in this pack with the least written detail.\"",
    ].join("\r\n");
  }

  /**
   * The full file plan. precedentsByTopic caps at maxTopicFiles topic files
   * (busiest first); everything else is one file each.
   */
  function buildPackPlan(ctx) {
    var files = [
      { name: "manifest.docx", kind: "docx", doc: manifestDoc(ctx) },
      { name: "people.docx", kind: "docx", doc: peopleDoc(ctx) },
      { name: "open-items.docx", kind: "docx", doc: openItemsDoc(ctx) },
      { name: "projects.docx", kind: "docx", doc: projectsDoc(ctx) },
      { name: "attachments.docx", kind: "docx", doc: attachmentsDoc(ctx) },
      { name: "Exit interview - " + safeName(ctx.ownerName, 40) + ".docx", kind: "docx", doc: interviewDoc(ctx) },
      { name: "README.txt", kind: "text", text: readmeText(ctx) },
      { name: "REVIEW-PROMPTS.txt", kind: "text", text: reviewPromptsText(ctx) },
    ];
    var byTopic = {};
    (ctx.precedents || []).forEach(function (p) {
      (byTopic[p.topicKey] = byTopic[p.topicKey] || []).push(p);
    });
    var topicKeys = Object.keys(byTopic)
      .sort(function (a, b) { return byTopic[b].length - byTopic[a].length || a.localeCompare(b); })
      .slice(0, ctx.maxTopicFiles || 40);
    topicKeys.forEach(function (k) {
      files.push({
        name: "precedents/" + safeName(byTopic[k][0].subject, 50) + ".docx",
        kind: "docx",
        doc: precedentTopicDoc(ctx, k, byTopic[k]),
      });
    });
    return files;
  }

  root.Pack = {
    buildPackPlan: buildPackPlan,
    _internals: { safeName: safeName, excerpt: excerpt, readmeText: readmeText },
  };
  if (typeof module !== "undefined" && module.exports) { module.exports = root.Pack; }
})(typeof self !== "undefined" ? self : this);
